"""LangGraph node implementations for the wealth advisor workflow."""
import re
import time
import uuid
from typing import List, Dict, Any
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai_client import get_async_client, chat_model
from app.graphs.state import GraphState, Citation
from app.rag.retriever import Retriever
from app.rag.reranker import Reranker
from app.rag.embedder import Embedder
from app.rag.parser import DocumentParser
from app.config import get_settings
from app.logging_config import get_logger

settings = get_settings()
logger = get_logger(__name__)

_pii_checker = DocumentParser(redact_pii=False)  # used only for detection, not redaction

SYSTEM_PROMPT = """You are a decision-support assistant helping financial advisors research regulatory filings and client documents.

This system is designed to assist human decision-making, not replace it. All outputs are for informational and research purposes only.

RULES:
1. Use ONLY the provided sources. Never make up information or speculate beyond what is cited.
2. If insufficient evidence, say "I don't have enough information to answer this."
3. Always cite sources using [1], [2], etc. Every factual claim must have a citation.
4. Never provide personalized investment advice or autonomous recommendations.
5. End with confidence level (High/Medium/Low) so the reviewer can calibrate trust."""

ASSISTIVE_DISCLAIMER = (
    "\n\n---\n"
    "_This response is generated by an AI decision-support system and is intended to assist, "
    "not replace, professional judgment. All information should be independently verified "
    "before use in client-facing communications or investment decisions._"
)

PROMPTS = {
    "qa": (
        "Answer this question based solely on the sources below. "
        "Do not speculate or add information not present in the sources.\n\n"
        "SOURCES:\n{sources}\n\nQUESTION: {query}"
    ),
    "summary": (
        "Summarize the following sources objectively. "
        "Do not draw conclusions beyond what the sources explicitly state.\n\n"
        "SOURCES:\n{sources}\n\nSUMMARIZE: {query}"
    ),
    "risk": (
        "Identify and analyze risks described in the sources below. "
        "Only report risks that are explicitly mentioned — do not infer or speculate.\n\n"
        "SOURCES:\n{sources}\n\nANALYSIS: {query}"
    ),
    "email": (
        "Draft a client email based on the sources below. "
        "Include a disclaimer that this is for educational and informational purposes only "
        "and does not constitute investment advice.\n\n"
        "SOURCES:\n{sources}\n\nREQUEST: {query}"
    ),
}

def build_refusal(state: GraphState) -> str:
    """
    Build a plain-language refusal message that explains *why* the system
    cannot answer, what it did try, and what the user can do next.
    This supports accessibility (transparent limitations) and human-centered
    workflow design (actionable guidance rather than a dead end).
    """
    reasons = []
    suggestions = []

    if state.flags.get("access_denied"):
        reasons.append("your account role does not permit access to the requested documents")
        suggestions.append("contact your administrator to request elevated access")
    elif state.flags.get("low_evidence"):
        count = len(state.retrieved_chunks)
        conf = state.flags.get("confidence", "low")
        if count == 0:
            reasons.append("no relevant documents were found in the approved document library")
            suggestions.append("upload the relevant filing or document first, then try again")
        else:
            reasons.append(
                f"only {count} relevant passage{'s' if count != 1 else ''} "
                f"were found and confidence was {conf} — insufficient to support a reliable answer"
            )
            suggestions.extend([
                "try narrowing your question to a specific filing, section, or company",
                "ensure the relevant documents have been ingested and approved",
            ])

    sources_searched = list({
        c.get("doc_title", "Unknown document")
        for c in state.retrieved_chunks
        if c.get("doc_title")
    })

    lines = ["**I was unable to answer this question.**", ""]
    if reasons:
        lines.append(f"**Why:** {'; '.join(reasons).capitalize()}.")
    if sources_searched:
        titles = ", ".join(f"*{t}*" for t in sources_searched[:5])
        lines.append(f"**Sources searched:** {titles}")
    else:
        lines.append("**Sources searched:** No matching documents found in the approved library.")
    if suggestions:
        lines.extend([
            "",
            "**What you can do:**",
            *[f"- {s.capitalize()}" for s in suggestions],
        ])

    lines += [
        "",
        "_This system only provides answers grounded in approved, ingested documents. "
        "If you believe this refusal is incorrect, you can flag this response for human review._",
    ]
    return "\n".join(lines)


class WorkflowNodes:
    """Node implementations for the LangGraph workflow."""
    
    def __init__(self, db: AsyncSession):
        self.db = db
        self.client = get_async_client()
        self.embedder = Embedder()
        self.retriever = Retriever(embedder=self.embedder)
        self.reranker = Reranker()
    
    async def intent_router(self, state: GraphState) -> GraphState:
        """Classify user intent and check query for PII."""
        _, pii_in_query = _pii_checker.redact_pii_content(state.user_query)
        if pii_in_query:
            state.flags["pii_detected"] = True

        prompt = f"Classify intent as qa/summary/risk/email:\n{state.user_query}\nRespond with one word."

        try:
            resp = await self.client.chat.completions.create(
                model=chat_model(),
                messages=[{"role": "user", "content": prompt}],
                max_tokens=10,
                temperature=0,
            )
            intent = resp.choices[0].message.content.strip().lower()
            state.intent = intent if intent in PROMPTS else "qa"
        except Exception:
            logger.warning("Intent classification failed, defaulting to 'qa'", exc_info=True)
            state.intent = "qa"

        return state
    
    async def retrieve_evidence(self, state: GraphState) -> GraphState:
        """Retrieve and rerank relevant chunks."""
        start = time.time()
        
        try:
            chunks = await self.retriever.retrieve(
                db=self.db,
                query=state.user_query,
                tenant_id=uuid.UUID(state.tenant_id),
                client_id=uuid.UUID(state.client_id) if state.client_id else None,
                doc_types=state.doc_types,
                company=state.company_filter,
                top_k=30,
                user_role=state.user_role,
            )
            
            reranked = await self.reranker.rerank(state.user_query, chunks, top_k=10)
            
            state.retrieved_chunks = [
                {
                    "id": str(r.chunk.id),
                    "document_id": str(r.chunk.document_id),
                    "content": r.chunk.content,
                    "chunk_metadata": r.chunk.metadata,
                    "doc_title": r.chunk.doc_title,
                    "source_url": r.chunk.source_url,
                    "rerank_score": r.rerank_score,
                }
                for r in reranked
            ]
            
            state.retrieval_scores = {
                str(r.chunk.id): {"vector": r.original_score, "rerank": r.rerank_score}
                for r in reranked
            }
            
            state.evidence_quality = self.reranker.compute_evidence_quality(reranked)
            
        except Exception as e:
            logger.error(
                "Evidence retrieval failed",
                extra={"conversation_id": state.conversation_id, "error": str(e)},
                exc_info=True,
            )
            state.error = str(e)
            state.retrieved_chunks = []
        
        state.latency_ms = int((time.time() - start) * 1000)
        return state
    
    async def check_evidence(self, state: GraphState) -> GraphState:
        """Check if evidence is sufficient."""
        count = len(state.retrieved_chunks)
        conf = state.evidence_quality.get("confidence", "low")
        
        state.has_sufficient_evidence = (
            (count >= 3 and conf in ["high", "medium"])
            or (count >= 1 and conf in ["high", "medium"])
            or (count >= 2 and conf == "low")
        )
        
        if not state.has_sufficient_evidence:
            state.flags["low_evidence"] = True
        state.flags["confidence"] = conf
        
        return state
    
    async def generate_response(self, state: GraphState) -> GraphState:
        """Generate response using LLM."""
        start = time.time()
        
        if not state.has_sufficient_evidence:
            state.draft_response = build_refusal(state)
            state.refusal_reason = (
                "access_denied" if state.flags.get("access_denied")
                else "low_evidence"
            )
            state.flags["advice_refused"] = True
            return state
        
        try:
            sources = self._format_sources(state.retrieved_chunks)
            user_prompt = PROMPTS.get(state.intent, PROMPTS["qa"]).format(sources=sources, query=state.user_query)
            
            resp = await self.client.chat.completions.create(
                model=chat_model(),
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                max_tokens=1500,
                temperature=0.3,
            )
            
            state.draft_response = resp.choices[0].message.content + ASSISTIVE_DISCLAIMER
            state.model_name = settings.OPENAI_CHAT_MODEL
            
        except Exception as e:
            logger.error(
                "Response generation failed",
                extra={"conversation_id": state.conversation_id, "intent": state.intent},
                exc_info=True,
            )
            state.draft_response = "An error occurred while generating a response. Please try again."
            state.error = str(e)
        
        state.latency_ms += int((time.time() - start) * 1000)
        return state
    
    async def format_citations(self, state: GraphState) -> GraphState:
        """Extract citations from response."""
        used = {int(m) for m in re.findall(r'\[(\d+)\]', state.draft_response)}
        
        state.citations = [
            Citation(
                chunk_id=chunk["id"],
                doc_title=chunk.get("doc_title", "Unknown"),
                section=chunk.get("chunk_metadata", {}).get("section", ""),
                quote=chunk["content"][:200] + "..." if len(chunk["content"]) > 200 else chunk["content"],
                page=chunk.get("chunk_metadata", {}).get("page"),
                url=chunk.get("source_url"),
            )
            for i, chunk in enumerate(state.retrieved_chunks, 1) if i in used
        ]
        
        state.final_response = state.draft_response

        _, pii_in_response = _pii_checker.redact_pii_content(state.draft_response)
        if pii_in_response:
            state.flags["pii_detected"] = True

        # Check for uncited claims
        sentences = re.split(r'[.!?]', state.draft_response)
        uncited = sum(len(s) > 50 and not re.search(r'\[\d+\]', s) for s in sentences)
        if uncited > 3:
            state.flags["possible_hallucination"] = True

        return state
    
    def _format_sources(self, chunks: List[Dict[str, Any]]) -> str:
        """Format top chunks as numbered sources, capped to ~4000 tokens total."""
        import tiktoken
        enc = tiktoken.get_encoding("cl100k_base")
        parts = []
        total_tokens = 0
        max_tokens = 4000

        for i, c in enumerate(chunks[:10], 1):
            meta = c.get("chunk_metadata", {})
            header = f"[{i}] {c.get('doc_title', 'Document')}"
            if meta.get("section"):
                header += f" - {meta['section']}"
            if meta.get("page"):
                header += f" (p.{meta['page']})"

            content = c["content"]
            entry = f"{header}\n{content}"
            entry_tokens = len(enc.encode(entry))

            if total_tokens + entry_tokens > max_tokens:
                # Truncate this chunk to fit remaining budget
                remaining = max_tokens - total_tokens
                if remaining < 100:
                    break
                content_tokens = enc.encode(content)[:remaining - len(enc.encode(header)) - 10]
                entry = f"{header}\n{enc.decode(content_tokens)}"

            parts.append(entry)
            total_tokens += len(enc.encode(entry))
            if total_tokens >= max_tokens:
                break

        return "\n\n---\n\n".join(parts)
